{
    parserClass="com.akestner.plugins.docker.lang.parser.DockerParser"
    parserUtilClass="org.intellij.grammar.parser.GeneratedParserUtilBase"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Docker"
    psiImplClassSuffix="Impl"
    psiPackage="com.akestner.plugins.docker.lang.psi"
    psiImplPackage="com.akestner.plugins.docker.lang.psi.impl"

    elementTypeHolderClass="com.akestner.plugins.docker.lang.psi.DockerTypes"
    elementTypeClass="com.akestner.plugins.docker.lang.psi.DockerElementType"
    tokenTypeClass="com.akestner.plugins.docker.lang.psi.DockerTokenType"

    tokens = [
        DOT='.'
        POUND='#'
        AT='@'
        DOLLAR='$'
        PLUS='+'
        COLON=':'
        SEMI_COLON=';'
        EQ='='
        COMMA=','
        DASH='-'
        UNDERSCORE='_'
        TILDA='~'
        BACKTICK='`'
        SINGLE_QT="'"
        DOUBLE_QT='"'
        FWD_SLASH='/'
        BACK_SLASH='\'
        RIGHT_CARET='>'
        LEFT_CARET='<'
        LEFT_PAREN='('
        RIGHT_PAREN=')'
        LEFT_BRACKET='['
        RIGHT_BRACKET=']'
        LEFT_CURLY_BRACKET='{'
        RIGHT_CURLY_BRACKET='}'

        // reserved words
        FROM="FROM"
        MAINTAINER="MAINTAINER"
        RUN="RUN"
        CMD="CMD"
        EXPOSE="EXPOSE"
        ENV="ENV"
        ADD="ADD"
        ENTRYPOINT="ENTRYPOINT"
        VOLUME="VOLUME"
        USER="USER"
        WORKDIR="WORKDIR"

        COMMENT='regexp:#.*$'
        NUMBER='regexp:\d+(\.\d*)?'
        ID='regexp:\p{Alpha}\w*'
        SHELL_CMD='regex:RUN\w*\p{Alpha}\w$'
        DOUBLE_QUOTED_STRING='regexp:(?:"([^"]*)")'
        SINGLE_QUOTED_STRING="regexp:(?:'([^']*)')"
    ]
}